### PR TITLE
run python-modernize

### PR DESCRIPTION
**Pull request by munk**
the result of `python-modernize -w src/python/*`

### CODE REVIEW

**Comment by MasterDDT** [comment]
To test this, can you:

- `./aiq compile all`
- update [this git hash](https://github.com/ActionIQ/aiq/blob/da37f20504b5cc2e72b04fb148da78059e81daf4/build-support/versions/pants-requirements.txt#L6) to match your changes
- `rm -rf ~/.cache`
- `rm -rf .pants.d`
- `./aiq compile all` // make sure this works, it should use the s3 pants plugin and pull everything from s3 cache

**Review by MasterDDT — APPROVED** [review]

**Comment by MasterDDT** [comment]
Have you checked the root repo (where we forked this from), have they fixed things up for py3?

**Comment by munk** [comment]
> Have you checked the root repo (where we forked this from), have they fixed things up for py3?

It hasn't been updated since we forked it.

**Comment by munk** [comment]
Test run looks good, merging

**Pull request merged**
