### PR TITLE
upgrade pants version

### PR DESCRIPTION
**Pull request by munk**
This is the first step in making this python3 compatible.

### CODE REVIEW

**Comment by MasterDDT** [comment]
Do we use pants to build this project? I thought we used setup.py, and then in AIQ we refer to it [like this](https://github.com/ActionIQ/aiq/blob/Pants1.16/build-support/versions/pants-requirements.txt#L6)

**Comment by LarryFinn** [comment]
@MasterDDT why wouldn't we build via pants?  bc we dont have a local py repository?  just curious

**Comment by MasterDDT** [comment]
> @MasterDDT why wouldn't we build via pants? bc we dont have a local py repository? just curious

Doing it via setup.py is easier because we can just point to a git commit and pip install right? Idk if there is a way to do that via pants? Just having one less thing that we need to publish sounds nice, I dont care what the build infra is. Def would prefer pants over setup.py in that regard.

**Comment by munk** [comment]
> Do we use pants to build this project? I thought we used setup.py, and then in AIQ we refer to it [like this](https://github.com/ActionIQ/aiq/blob/Pants1.16/build-support/versions/pants-requirements.txt#L6)

You're right, it looks like we point to the egg from setup.py. My next step is to write some tests for this, so I can update it to be forward compatible. I am planning on running those tests via pants, but I might be able to run them with vanilla pytest also. Do you have a preference? @MasterDDT @LarryFinn

**Comment by MasterDDT** [comment]
> > Do we use pants to build this project? I thought we used setup.py, and then in AIQ we refer to it [like this](https://github.com/ActionIQ/aiq/blob/Pants1.16/build-support/versions/pants-requirements.txt#L6)
> 
> You're right, it looks like we point to the egg from setup.py. My next step is to write some tests for this, so I can update it to be forward compatible. I am planning on running those tests via pants, but I might be able to run them with vanilla pytest also. Do you have a preference? @MasterDDT @LarryFinn

I def dont have a pref haha. Do we even need tests on this plugin? I suppose thats a FS question, incl @alexmoore0

**Comment by munk** [comment]
> > > Do we use pants to build this project? I thought we used setup.py, and then in AIQ we refer to it [like this](https://github.com/ActionIQ/aiq/blob/Pants1.16/build-support/versions/pants-requirements.txt#L6)
> > 
> > 
> > You're right, it looks like we point to the egg from setup.py. My next step is to write some tests for this, so I can update it to be forward compatible. I am planning on running those tests via pants, but I might be able to run them with vanilla pytest also. Do you have a preference? @MasterDDT @LarryFinn
> 
> I def dont have a pref haha. Do we even need tests on this plugin? I suppose thats a FS question, incl @alexmoore0

There are a couple of places with relative imports that need to be exercised. Because python isn't compiled, tests are the best way to make sure that it still works after modernizing.

**Review by MasterDDT — APPROVED** [review]
are we gonna have automated tests for this running in travis?

**Comment by munk** [comment]
> are we gonna have automated tests for this running in travis?

That's not a bad idea. Travis is free for open source projects?

**Pull request merged**
